INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('BANANE', 3); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('SUCRE BLANC', 75); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('OEUF', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('LEVURE', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('SEL', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('FARINE', 150); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('BEURRE', 70);
